# Generated by Django 2.2.7 on 2019-11-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=40)),
                ('property_number', models.IntegerField()),
                ('image', models.ImageField(default='default_vehicle.jpg', upload_to='vehicle_profile_pics')),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
            ],
        ),
    ]
