# Generated by Django 2.2.7 on 2019-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20191119_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicunit',
            name='year',
            field=models.IntegerField(default='2000'),
        ),
    ]
