# Generated by Django 2.2.7 on 2019-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_medicunit_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('conentration', models.CharField(max_length=40)),
            ],
        ),
    ]
