# Generated by Django 2.2.7 on 2019-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_drug_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='total',
        ),
        migrations.AddField(
            model_name='drug',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
