# Generated by Django 2.2.7 on 2019-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20191204_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicunit',
            name='property_number',
            field=models.IntegerField(unique=True),
        ),
    ]
