# Generated by Django 2.2.7 on 2020-01-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191122_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('EMS 901', 'EMS 901'), ('EMS 902', 'EMS 902')], max_length=100),
        ),
    ]
