# Generated by Django 2.2.7 on 2020-02-08 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0013_auto_20191217_1112'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSIBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('RSI_seal_number', models.IntegerField()),
                ('incident_number', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=50)),
                ('contact_EMS_Chief', models.CharField(default='', max_length=100)),
                ('free_text', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NarcBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('seal_number', models.IntegerField(unique=True)),
                ('amount_removed_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_added_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_in_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('incident_number', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=50)),
                ('narc_box_free_text', models.TextField(blank=True, default='')),
                ('narc_name', models.ForeignKey(default=0, limit_choices_to={'is_active_unit': True}, on_delete=django.db.models.deletion.PROTECT, related_name='narc_name', to='components.Drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('mileage', models.IntegerField(default=0)),
                ('emergency_lights', models.BooleanField()),
                ('driving_lights', models.BooleanField()),
                ('red_bag', models.BooleanField()),
                ('LP_15', models.BooleanField()),
                ('BLS_bag', models.BooleanField()),
                ('RTF_bag', models.BooleanField()),
                ('suction', models.BooleanField()),
                ('oxygen', models.BooleanField()),
                ('free_text', models.TextField(default='')),
                ('daily_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medic_unit_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='medic_unit_number', to='components.MedicUnit')),
                ('narc_seal_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narcbox_seal_number', to='checks.NarcBox', to_field='seal_number')),
                ('unit_property_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='unit_property_number', to='components.Vehicle')),
            ],
        ),
    ]
