# Generated by Django 2.2.7 on 2020-05-24 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_record_date', models.DateTimeField(auto_now=True)),
                ('engine_oil', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('transmission_fluid', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('brake_fluid', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('coolant', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('LUCAS_device', models.CharField(choices=[('Functional', 'Functional'), ('Needs Repair', 'Needs Repair')], default='Functional', max_length=30)),
                ('EMS_equipment', models.CharField(choices=[('All equiment is present, functional and in date', 'All equiment is present, functional and in date'), ('Some euipment missing (See Comments)', 'Some euipment missing (See Comments)'), ('Items out of date (See Comments)', 'Items out of date (See Comments)')], default='All equiment is present, functional and in date', max_length=50)),
                ('suciton_unit', models.CharField(choices=[('Charged', 'Charged'), ('On Charge', 'On Charge'), ('Not Charging', 'Not Charging')], default='Charged', max_length=30)),
                ('driver_front_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30)),
                ('driver_rear_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30)),
                ('passenger_front_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30)),
                ('passenger_rear_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('weekly_unit_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='weekly_unit_number', to='components.MedicUnit')),
                ('weekly_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSIBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('RSI_seal_number', models.IntegerField()),
                ('next_expiration_date', models.DateField(default=datetime.datetime.now)),
                ('incident_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_EMS_Chief', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('free_text', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NarcBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('seal_number', models.IntegerField()),
                ('amount_given_to_patient', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_removed_from_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_added_to_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_in_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('incident_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('narc_box_free_text', models.TextField(blank=True, default='')),
                ('narc_medic_unit_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='narc_medic_unit_number', to='components.MedicUnit')),
                ('narcotic_name', models.ForeignKey(default=0, limit_choices_to={'is_active_unit': True}, on_delete=django.db.models.deletion.PROTECT, related_name='narc_name', to='components.Drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('mileage', models.IntegerField(default=0)),
                ('emergency_lights', models.BooleanField()),
                ('driving_lights', models.BooleanField()),
                ('red_bag', models.BooleanField()),
                ('LP_15', models.BooleanField()),
                ('BLS_bag', models.BooleanField()),
                ('RTF_bag', models.BooleanField()),
                ('suction', models.BooleanField()),
                ('oxygen', models.BooleanField()),
                ('free_text', models.TextField(default='')),
                ('daily_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medic_unit_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='medic_unit_number', to='components.MedicUnit')),
                ('unit_property_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='unit_property_number', to='components.Vehicle')),
            ],
        ),
    ]
