# Generated by Django 2.2.7 on 2020-02-15 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20191217_1112'),
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narcbox',
            old_name='amount_added_unit',
            new_name='amount_added_to_unit',
        ),
        migrations.RenameField(
            model_name='narcbox',
            old_name='amount_removed_unit',
            new_name='amount_removed_from_unit',
        ),
        migrations.RenameField(
            model_name='narcbox',
            old_name='narc_name',
            new_name='narcotic_name',
        ),
        migrations.RemoveField(
            model_name='dailycheck',
            name='narc_seal_number',
        ),
        migrations.AddField(
            model_name='narcbox',
            name='amount_given_to_patient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='narcbox',
            name='narc_medic_unit_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='narc_medic_unit_number', to='components.MedicUnit'),
        ),
        migrations.AlterField(
            model_name='narcbox',
            name='seal_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rsibag',
            name='contact_EMS_Chief',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
