# Generated by Django 2.2.7 on 2020-05-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsibag',
            name='RSI_unit_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='RSI_unit_number', to='components.MedicUnit'),
        ),
    ]
