# Generated by Django 2.2.7 on 2020-03-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20200215_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsibag',
            name='next_expiration_date',
            field=models.DateField(default='2020-03-09'),
        ),
    ]
