# Generated by Django 2.2.7 on 2020-03-12 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0014_medicunit_is_supervisor'),
        ('checks', '0005_auto_20200309_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_record_date', models.DateTimeField(auto_now=True)),
                ('engine_oil', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('transmission_fluid', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('brake_fluid', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('collant', models.CharField(choices=[('Within Range', 'Within Range'), ('Needs More', 'Needs More')], default='Within Range', max_length=20)),
                ('LUCAS_device', models.CharField(choices=[('Functional', 'Functional'), ('Needs Repair', 'Needs Repair')], default='Functional', max_length=30)),
                ('EMS_equipment', models.CharField(choices=[('All equiment is present, functional and in date', 'All equiment is present, functional and in date'), ('Some euipment missing (See Comments)', 'Some euipment missing (See Comments)'), ('Items out of date (See Comments)', 'Items out of date (See Comments)')], default='All equiment is present, functional and in date', max_length=40)),
                ('suciton_unit', models.CharField(choices=[('Charged', 'Charged'), ('On Charge', 'On Charge'), ('Not Charging', 'Not Charging')], default='Charged', max_length=30)),
                ('driver_front_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], max_length=30)),
                ('driver_rear_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], max_length=30)),
                ('passenger_front_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], max_length=30)),
                ('passenger_rear_tire', models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('weekly_unit_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='weekly_unit_number', to='components.MedicUnit')),
                ('weekly_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
