# Generated by Django 2.2.7 on 2020-03-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0007_auto_20200312_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycheck',
            name='driver_front_tire',
            field=models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklycheck',
            name='driver_rear_tire',
            field=models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklycheck',
            name='passenger_front_tire',
            field=models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklycheck',
            name='passenger_rear_tire',
            field=models.CharField(choices=[('Full', 'Full'), ('Low', 'Low'), ('Flat', 'Flat')], default='Full', max_length=30),
        ),
    ]
