# Generated by Django 2.2.7 on 2020-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0009_auto_20200312_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narcbox',
            name='incident_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
