# Generated by Django 2.2.7 on 2020-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0010_auto_20200313_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narcbox',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
