# Generated by Django 2.2.7 on 2020-01-12 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0013_auto_20191217_1112'),
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('mileage', models.IntegerField(default=0)),
                ('emergency_lights', models.BooleanField()),
                ('driving_lights', models.BooleanField()),
                ('red_bag', models.BooleanField()),
                ('LP_15', models.BooleanField()),
                ('BLS_bag', models.BooleanField()),
                ('RTF_bag', models.BooleanField()),
                ('suction', models.BooleanField()),
                ('oxygen', models.BooleanField()),
                ('free_text', models.TextField(default='')),
                ('daily_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medic_unit_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='medic_unit_number', to='components.MedicUnit')),
                ('unit_property_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='unit_property_number', to='components.Vehicle')),
            ],
        ),
    ]
