# Generated by Django 2.2.7 on 2020-01-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20191217_1112'),
        ('checks', '0002_dailycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='narcbox',
            name='amount_added_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='narcbox',
            name='amount_in_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='narcbox',
            name='amount_removed_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='narcbox',
            name='narc_name',
            field=models.ForeignKey(default=0, limit_choices_to={'is_active_unit': True}, on_delete=django.db.models.deletion.PROTECT, related_name='narc_name', to='components.Drug'),
        ),
    ]
