# Generated by Django 2.2.7 on 2020-03-09 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_rsibag_next_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsibag',
            name='contact_EMS_Chief',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='rsibag',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rsibag',
            name='incident_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
