# Generated by Django 2.2.7 on 2020-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_auto_20200118_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='narcbox',
            name='narc_box_free_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
