# Generated by Django 2.2.7 on 2020-03-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0006_weeklycheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklycheck',
            old_name='collant',
            new_name='coolant',
        ),
    ]
