# Generated by Django 2.2.7 on 2020-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0008_auto_20200312_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycheck',
            name='EMS_equipment',
            field=models.CharField(choices=[('All equiment is present, functional and in date', 'All equiment is present, functional and in date'), ('Some euipment missing (See Comments)', 'Some euipment missing (See Comments)'), ('Items out of date (See Comments)', 'Items out of date (See Comments)')], default='All equiment is present, functional and in date', max_length=50),
        ),
    ]
