# Generated by Django 2.2.7 on 2019-11-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_drug_total'),
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safeadd',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='saferemove',
            name='drug',
        ),
        migrations.AddField(
            model_name='safeadd',
            name='drug_add',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='drug_add', to='components.Drug'),
        ),
        migrations.AddField(
            model_name='saferemove',
            name='drug_remove',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='drug_remove', to='components.Drug'),
        ),
        migrations.AddField(
            model_name='saferemove',
            name='incident_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='saferemove',
            name='patient_name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
