# Generated by Django 2.2.7 on 2019-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_auto_20191120_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='saferemove',
            name='free_text',
            field=models.CharField(blank=True, default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='saferemove',
            name='incident_number',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='saferemove',
            name='patient_name',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
