# Generated by Django 2.2.7 on 2019-11-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0009_auto_20191121_0843'),
        ('safe', '0004_auto_20191120_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('amount_removed', models.IntegerField()),
                ('amount_added', models.IntegerField()),
                ('incident_number', models.CharField(blank=True, default=0, max_length=20)),
                ('patient_name', models.CharField(blank=True, default=0, max_length=20)),
                ('free_text', models.CharField(blank=True, default=0, max_length=1000)),
                ('drug_total', models.IntegerField()),
                ('drug_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='drug_remove', to='components.Drug')),
                ('medic_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medic_unit', to='components.MedicUnit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='safecheck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saferemove',
            name='drug_name',
        ),
        migrations.RemoveField(
            model_name='saferemove',
            name='user',
        ),
        migrations.DeleteModel(
            name='SafeAdd',
        ),
        migrations.DeleteModel(
            name='SafeCheck',
        ),
        migrations.DeleteModel(
            name='SafeRemove',
        ),
    ]
