# Generated by Django 2.2.7 on 2019-11-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0005_auto_20191121_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='amount_added',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='safe',
            name='amount_removed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='safe',
            name='drug_total',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='safe',
            name='medic_unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='medic_unit', to='components.MedicUnit'),
        ),
    ]
