# Generated by Django 2.2.7 on 2019-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0006_auto_20191121_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='amount_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safe',
            name='amount_removed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
