# Generated by Django 2.2.7 on 2019-11-21 16:06

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_auto_20191121_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='drug_total',
            field=computed_property.fields.ComputedIntegerField(compute_from='add_drug', editable=False),
        ),
    ]
