# Generated by Django 2.2.7 on 2019-11-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0008_auto_20191121_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safe',
            name='drug_total',
        ),
    ]
