# Generated by Django 2.2.7 on 2019-11-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0009_remove_safe_drug_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='medic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medic_unit', to='components.MedicUnit'),
        ),
    ]
