# Generated by Django 2.2.7 on 2019-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0010_auto_20191122_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='amount_confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
