# Generated by Django 2.2.7 on 2019-11-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0011_safe_amount_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safe',
            old_name='amount_confirmed',
            new_name='amount_in_safe',
        ),
    ]
