# Generated by Django 2.2.7 on 2019-11-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0012_auto_20191122_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='drug_name',
            field=models.ForeignKey(default=0, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='drug_remove', to='components.Drug'),
        ),
    ]
