# Generated by Django 2.2.7 on 2019-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0013_auto_20191123_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='free_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='safe',
            name='incident_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='safe',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
