# Generated by Django 2.2.7 on 2019-11-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0014_auto_20191125_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='free_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
