# Generated by Django 2.2.7 on 2019-12-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0015_auto_20191125_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='drug_name',
            field=models.ForeignKey(default=0, limit_choices_to={'is_active_safe': True}, on_delete=django.db.models.deletion.PROTECT, related_name='drug_remove', to='components.Drug'),
        ),
    ]
