# Generated by Django 2.2.7 on 2019-12-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0018_auto_20191213_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safe',
            options={'permissions': (('can_view_safe', 'Can view safe'),)},
        ),
    ]
