# Generated by Django 2.2.7 on 2019-12-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0019_auto_20191213_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safe',
            options={'permissions': (('can_view', 'Can view safe'),)},
        ),
    ]
