# Generated by Django 2.2.7 on 2019-12-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0021_auto_20191213_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safe',
            options={'permissions': (('can_view', 'Fuck You'),)},
        ),
    ]
