# Generated by Django 2.2.7 on 2019-12-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0022_auto_20191213_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safe',
            options={'permissions': (('can_view', 'Fuck You'), ('can_add', 'Add to the Safe'))},
        ),
    ]
