# Generated by Django 2.2.7 on 2019-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_medicunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicunit',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='medicunit',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicunit',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicunit',
            name='unit_number',
            field=models.IntegerField(default='0'),
        ),
    ]
