# Generated by Django 2.2.7 on 2019-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20191119_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicunit',
            name='mileage',
            field=models.IntegerField(default='0'),
        ),
    ]
