# Generated by Django 2.2.7 on 2019-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_drug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='conentration',
            new_name='concentration',
        ),
        migrations.AddField(
            model_name='drug',
            name='image',
            field=models.ImageField(default='default_drug.png', upload_to='drug_pics'),
        ),
    ]
