# Generated by Django 2.2.7 on 2019-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20191120_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
