# Generated by Django 2.2.7 on 2019-12-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_auto_20191216_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicunit',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='medicunit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='medicunit',
            name='make',
        ),
        migrations.RemoveField(
            model_name='medicunit',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='medicunit',
            name='model',
        ),
        migrations.RemoveField(
            model_name='medicunit',
            name='property_number',
        ),
        migrations.RemoveField(
            model_name='medicunit',
            name='unit_number',
        ),
        migrations.RemoveField(
            model_name='medicunit',
            name='year',
        ),
        migrations.AddField(
            model_name='medicunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicunit',
            name='unit_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.IntegerField()),
                ('image', models.ImageField(default='default_vehicle.jpg', upload_to='vehicle_profile_pics')),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('year', models.IntegerField(default='2000')),
                ('date_created', models.DateField(auto_now=True)),
                ('mileage', models.IntegerField(default='0')),
                ('unit_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.MedicUnit')),
            ],
        ),
    ]
