# Generated by Django 2.2.7 on 2020-03-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20191217_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicunit',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
